# Generated by Django 4.1.3 on 2022-11-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
