# Generated by Django 4.1.3 on 2022-11-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
